GET http://localhost:3001/todos HTTP/1.1
###

POST http://localhost:3001/todo/new 
Content-Type: application/json

{
"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/63fce2295fab9823a3a21a22
###

GET http://localhost:3001/todo/complete/63fcdfb2e0d284c4ebfee1a8

###

PUT http://localhost:3001/todo/update/63fce18fa7714d1c89415c87 
Content-Type: application/json

{
"text": "Go Shopping for Milk"
}